version: '3'

services:
  # node:
  #   build:
  #     context: ./node
  #     dockerfile: Dockerfile
  #   image: lmgomes91/node:prod
  #   container_name: node
  #   ports:
  #     - 3000:3000

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
